openapi: 3.0.1
info:
  title: apiops
  description: Import from "apiops" Function App
  version: ''
servers:
  - url: https://apiops.azure-api.net/apiops
paths:
  /todo:
    get:
      summary: GetTodos
      operationId: get-gettodos
      responses:
        '200':
          description: 
    post:
      summary: CreateTodo
      operationId: post-createtodo
      responses:
        '200':
          description: 
  '/todo/{id}':
    get:
      summary: GetTodoById
      operationId: get-gettodobyid
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: ''
      responses:
        '200':
          description: 
    delete:
      summary: DeleteTodo
      operationId: delete-deletetodo
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: ''
      responses:
        '200':
          description: 
    put:
      summary: UpdateTodo
      operationId: put-updatetodo
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: ''
      responses:
        '200':
          description: 
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]