apimServiceName: apim-prod-wk-03022022
namedValues:
  - name: TestToken
    displayName: TestToken
    value: myprodtoken
#products:
#  - name: vipproduct
#    description: This is a custom description from the config file
#    terms: This is a custom term from the config file
#    apis:
#      - name: demo-conference-api
#gateways:
#  - name: MyCustomGateway
#    description: my custom gateway description from config file
#    apis:
#      - name: demo-conference-api
#loggers:
#    - name: apim-lab-insights
#      loggerType: applicationInsights
#      description: apim lab prod app insights
#      resourceId: "/subscriptions/77fadbdc-74f1-4ce8-8962-b34400a1f170/resourceGroups/rg-apim-lab-prod/providers/microsoft.insights/components/apim-lab-prod-insights"
#      credentials:
#        connectionString: "InstrumentationKey=339f10b6-7c47-45b4-8622-afcdb5bac612;IngestionEndpoint=https://eastus-8.in.applicationinsights.azure.com/"
#        #instrumentationKey: 339f10b6-7c47-45b4-8622-afcdb5bac612
#      isBuffered: true
#diagnostics:
#   - name: apim-lab-insights
#     verbosity: Information
