name: Run - Creator

on:
   # Triggers the workflow on pull request events but only for the main branch
  pull_request:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  get-commit:
    runs-on: ubuntu-latest
    steps:
      # Set the COMMIT_ID env variable
      - name: Set the Commit Id
        id: commit
        run: |
          echo "::set-output name=commit_id::${GITHUB_SHA}"
    outputs:
          commit_id: ${{ steps.commit.outputs.commit_id }}
  create-dev:
    needs: get-commit
    uses: ./.github/workflows/run-extractor-with-env.yaml
    with:
      AZURE_RESOURCE_GROUP_NAME: apim-devops
      API_MANAGEMENT_SERVICE_NAME: apiops
      API_MANAGEMENT_ENVIRONMENT: dev    
      COMMIT_ID: ${{ needs.get-commit.outputs.commit_id }} 
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}     
  create-prod:
    needs: [get-commit, create-dev]
    uses: ./.github/workflows/run-extractor-with-env.yaml
    with:
      AZURE_RESOURCE_GROUP_NAME: apim-devops
      API_MANAGEMENT_SERVICE_NAME: apiops
      API_MANAGEMENT_ENVIRONMENT: prod
      COMMIT_ID: ${{ needs.get-commit.outputs.commit_id }}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
