name: run-extractor-with-env

on:
  workflow_call:
    inputs:
      AZURE_RESOURCE_GROUP_NAME:
        required: true
        type: string
      API_MANAGEMENT_SERVICE_NAME: 
        required: true
        type: string
      API_MANAGEMENT_ENVIRONMENT: 
        required: true
        type: string        
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_CLIENT_SECRET:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true        
        
jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
          
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: publish-extractor.yaml
          name: extractor
          
      - name: Run extractor
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_RESOURCE_GROUP_NAME: ${{ inputs.AZURE_RESOURCE_GROUP_NAME }}
          API_MANAGEMENT_SERVICE_NAME: ${{ inputs.API_MANAGEMENT_SERVICE_NAME }}
          API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH: ${{ GITHUB.WORKSPACE }}/${{ inputs.API_MANAGEMENT_SERVICE_NAME }}-${{ inputs.API_MANAGEMENT_ENVIRONMENT }}
        run: |
          chmod +x ./extractor
          ./extractor
          ls -la ${{ inputs.API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH }}
      - name: publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifacts-from-portal
          path: ${{ GITHUB.WORKSPACE }}/${{ inputs.API_MANAGEMENT_SERVICE_NAME }}-${{ inputs.API_MANAGEMENT_ENVIRONMENT }}     
          
  create-pull-request:
    needs: extract
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
          
      - name: Download artifacts-from-portal
        uses: actions/download-artifact@v2
        with:
          name: artifacts-from-portal
          path: "${{ GITHUB.WORKSPACE }}/${{ inputs.API_MANAGEMENT_SERVICE_NAME }}-${{ inputs.API_MANAGEMENT_ENVIRONMENT }}"

      - name: Create artifacts pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "updated extract from apim instance ${{ inputs.API_MANAGEMENT_SERVICE_NAME }}"
          title: "${{ inputs.API_MANAGEMENT_SERVICE_NAME }} - extract"
          body: >
            This PR is auto-generated by Github actions workflow
          labels: extract, automated pr
