name: Run - Creator

on:
   # Triggers the workflow on pull request events but only for the main branch
  pull_request:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  AZURE_RESOURCE_GROUP_NAME_DEV: apim-devops  # Replace this value with your resource group name
  API_MANAGEMENT_SERVICE_NAME_DEV: apiops  # Replace this value with yourapim instance name 
  API_MANAGEMENT_ENVIRONMENT_DEV: dev
  AZURE_RESOURCE_GROUP_NAME_PROD: apim-devops  # Replace this value with your resource group name
  API_MANAGEMENT_SERVICE_NAME_PROD: apiops  # Replace this value with yourapim instance name 
  API_MANAGEMENT_ENVIRONMENT_PROD: prod

jobs:
  get-commit:
    runs-on: ubuntu-latest
    steps:
      # Set the COMMIT_ID env variable
      - name: Set the Commit Id
        id: commit
        run: |
          echo "::set-output name=commit_id::${GITHUB_SHA}"
    outputs:
          commit_id: ${{ steps.commit.outputs.commit_id }}
  create-dev:
    runs-on: ubuntu-latest
    environment: dev   
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      # Download the Creator binary
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: publish-creator.yaml
          name: creator         

      - name: Run creator without Config Yaml
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_RESOURCE_GROUP_NAME: ${{ env.AZURE_RESOURCE_GROUP_NAME_DEV }}
          API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH: ${{ GITHUB.WORKSPACE }}/${{ env.API_MANAGEMENT_SERVICE_NAME_DEV }}-${{ env.API_MANAGEMENT_ENVIRONMENT_DEV }}
          COMMIT_ID: ${{ needs.get-commit.outputs.commit_id }}
        run: |
          chmod +x ./creator
          ./creator     
  create-prod:
    runs-on: ubuntu-latest
    needs: [get-commit, create-dev]
    environment: prod  
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      # Download the Creator binary
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: publish-creator.yaml
          name: creator         

      - name: Run creator with Config Yaml
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_RESOURCE_GROUP_NAME: ${{ env.AZURE_RESOURCE_GROUP_NAME_PROD }}
          API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH: ${{ GITHUB.WORKSPACE }}/${{ env.API_MANAGEMENT_SERVICE_NAME_PROD }}-${{ env.API_MANAGEMENT_ENVIRONMENT_PROD }}
          CONFIGURATION_YAML_PATH:  ${{ env.CONFIGURATION_YAML_PATH_PROD }}
          COMMIT_ID: ${{ needs.get-commit.outputs.commit_id }}
        run: |
          chmod +x ./creator
          ./creator   
