name: Run Extractor

on:
  workflow_dispatch:
  
jobs:
  extract:
    uses: ./.github/workflows/run-extractor-with-env.yaml
    with:
      AZURE_RESOURCE_GROUP_NAME: apim-devops
      API_MANAGEMENT_SERVICE_NAME: apiops
      API_MANAGEMENT_ENVIRONMENT: dev    
